### ISSUE TITLE
breath in repetition causes validation error

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#72]
Adding breath to an instruction inside a repetition causes a validation error. jasiMasters2024011201.xml

```
<!-- not valid -->
<instruction>
    <repetition>
        <repetitionCount>4</repetitionCount>
        <simplify>true</simplify>
        <equipment>fins</equipment>
        <instruction>
            <length>
                <lengthAsDistance>100</lengthAsDistance>
            </length>
            <stroke>
                <standardStroke>freestyle</standardStroke>
            </stroke>
            <breath>5</breath>
        </instruction>
    </repetition>
</instruction>

<!-- valid -->
<instruction>
    <length>
        <lengthAsDistance>100</lengthAsDistance>
    </length>
    <stroke><standardStroke>freestyle</standardStroke></stroke>
    <breath>5</breath>
</instruction>
```

**Comment by calloc262** [comment]
fixed with commit to main

**Comment by bartneck** [comment]
Was this changed for both 2.0 (in the versions folder) and the 2.1 (in the root folder)? I still get the validation error.

**Comment by bartneck** [comment]
I am sorry, but I still get the same validation error. I guess we have to re-open the issue.
![Uploading Screenshot 2024-02-02 at 3.42.33 PM.png…]()

**Comment by calloc262** [comment]
I can't seem to replicate this issue with the same code as above
with either 2.0 or 2.1.
I also can't find jasiMasters2024011201.xml
where would this be?

**Comment by bartneck** [comment]
Seems to have been resolved now. I do not know why. I will close this issue for now.
